"""add last_checked_at column to product model

Revision ID: 0b68416a3754
Revises: 8cb04598c469
Create Date: 2026-03-10 09:16:37.616396

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b68416a3754"
down_revision: Union[str, None] = "8cb04598c469"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("last_checked_at", sa.DateTime(), nullable=True))

    op.execute(
        """
            UPDATE products
            SET last_checked_at = (SELECT created_at
            FROM productprices
            WHERE productprices.product_id = products.id
                              ORDER BY productprices.created_at DESC LIMIT 1)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "last_checked_at")
    # ### end Alembic commands ###
