"""models refact

Revision ID: 2e7c0b4680e3
Revises: 7de7d7d83c76
Create Date: 2025-03-20 10:26:33.137883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e7c0b4680e3"
down_revision: Union[str, None] = "7de7d7d83c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productprices",
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_products",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "product_id"),
    )
    op.drop_constraint("products_user_id_fkey", "products", type_="foreignkey")
    op.drop_column("products", "user_id")
    op.drop_column("products", "price")
    op.add_column("users", sa.Column("username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.add_column("products", sa.Column("price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column("products", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("products_user_id_fkey", "products", "users", ["user_id"], ["id"])
    op.drop_table("user_products")
    op.drop_table("productprices")
    # ### end Alembic commands ###
