"""number and sku_id fields added to Product table

Revision ID: 7de7d7d83c76
Revises: fc0a89131bdb
Create Date: 2025-03-18 09:50:23.303727

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7de7d7d83c76"
down_revision: Union[str, None] = "fc0a89131bdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("number", sa.String(), nullable=False))
    op.add_column("products", sa.Column("sku_id", sa.String(), nullable=True))
    op.alter_column("products", "title", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("products", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True)
    op.create_unique_constraint("unique_product", "products", ["number", "sku_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_product", "products", type_="unique")
    op.alter_column("products", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False)
    op.alter_column("products", "title", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("products", "sku_id")
    op.drop_column("products", "number")
    # ### end Alembic commands ###
