"""add last_price column to product model

Revision ID: 8cb04598c469
Revises: cd1b312aecb6
Create Date: 2026-03-07 20:17:08.458929

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cb04598c469"
down_revision: Union[str, None] = "cd1b312aecb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("last_price", sa.Float(), nullable=True))

    op.execute(
        """
            UPDATE products
            SET last_price = (SELECT price
            FROM productprices
            WHERE productprices.product_id = products.id
                              ORDER BY productprices.created_at DESC LIMIT 1)
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "last_price")
    # ### end Alembic commands ###
