"""Added unique_user_product uniqueconstraint

Revision ID: cd1b312aecb6
Revises: 2e7c0b4680e3
Create Date: 2026-02-26 16:15:29.213560

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd1b312aecb6"
down_revision: Union[str, None] = "2e7c0b4680e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_user_product", "user_products", ["user_id", "product_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_product", "user_products", type_="unique")
    # ### end Alembic commands ###
